# Site settings
remote_theme: cayman
title: 阿常与山海
header-img: "img/Xacebook.jpg"
tagline: "cn"  
description: "摄影、游记、记录"  
baseurl: ""
url: "https://chchangzh.github.io/"  

# Site settings
title: 常甲chchangzh   				  	#你博客的标题
SEOTitle: 常甲 | chchangzh    	 #显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-rwd.jpg  	#显示在首页的背景图片
email: 1023813421@qq.com	
description: "摄影日常生活记录"  			 #网站介绍
keyword: "摄影, 博客, 分享, 照片, 图片, 壁纸, 碎片, 记录" #关键词
url: "https://chchangzh.github.io/"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写

# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "出来交个朋友啊"
sidebar-avatar:/img/avatar-by.JPG      # 你的个人头像 这里你可以改成我在img文件夹中的两张备用照片 img/avatar-m 或 avatar-g
